from __future__ import annotations

import asyncio
from datetime import date
from pathlib import Path

import docx

from scheduler_agents.flows.scheduler_flow import SchedulerFlow
from scheduler_agents.models.state import TimesheetData
from scheduler_agents.tools.invoice_tool import fill_invoice_template
from scheduler_agents.tools.timesheet_tool import parse_purchase_order_pdf, parse_purchase_order_text

SAMPLE_DATA = Path(__file__).resolve().parents[1] / "sample_data"

# Real extracted-text shape from an actual vendor Purchase Order PDF
# (values changed; the layout/wording is what matters for the regexes).
REAL_SHAPED_PO_TEXT = """
PURCHASE ORDER
For the attention of
000000 Jane Doe
123 Example Street
33
Sample City, Example Country [XX]
Job ID Description
2026/2609/#1/1 000000_Jane Doe_March 2026
Language pair Job type Specialisation
EN-GB » FA interpreting (telephone) Social Services
Delivered to Start date Deadline
Alina Barila Apr 7, 2026 Apr 7, 2026
Calculation unit Quantity Price Amount
1h 40.53 8.0000 324.24
Subtotal € 324.24
2026/2609/#1/1 —Total €324.24
+42 1944314030 http://www.glocco.sk
hello@glocco.sk
Generated by XTRF®
www.xtrf.eu
"""


def test_parse_purchase_order_text_extracts_job_id_period_and_total():
    data = parse_purchase_order_text(REAL_SHAPED_PO_TEXT)

    assert data is not None
    assert data.job_id == "2026/2609/#1/1"
    assert data.period == "March 2026"
    assert data.total_amount == 324.24


def test_parse_purchase_order_text_uses_total_not_subtotal():
    # Subtotal and Total differ (e.g. an adjustment) -- must pick Total.
    text = REAL_SHAPED_PO_TEXT.replace("Subtotal € 324.24", "Subtotal € 300.00")

    data = parse_purchase_order_text(text)

    assert data.total_amount == 324.24


def test_parse_purchase_order_text_returns_none_when_fields_missing():
    assert parse_purchase_order_text("Please find attached the Purchase Order.") is None


def test_fill_invoice_template_updates_only_monthly_fields(tmp_path: Path):
    data = TimesheetData(job_id="2026/9999/#1/1", period="September 2026", total_amount=123.45)
    output_path = tmp_path / "invoice_out.docx"

    fill_invoice_template(
        SAMPLE_DATA / "invoice_template.docx",
        output_path,
        data,
        vendor_id="000000",
        invoice_date=date(2026, 9, 15),
    )

    doc = docx.Document(str(output_path))
    header_table = doc.tables[0]
    line_items_table = doc.tables[2]

    assert header_table.rows[3].cells[1].paragraphs[1].text == "000000/202609"
    assert header_table.rows[3].cells[2].paragraphs[1].text == "15/09/2026"
    assert line_items_table.rows[2].cells[0].paragraphs[0].text == "2026/9999/#1/1"
    assert line_items_table.rows[2].cells[2].paragraphs[0].text == "€ 123.45"
    assert line_items_table.rows[3].cells[2].paragraphs[0].text == "€ 123.45"

    # Static fields (name/address/bill-to) must be untouched.
    assert "Jane Doe" in header_table.rows[1].cells[0].paragraphs[0].text
    assert "GLOCCO" in doc.tables[1].rows[1].cells[0].paragraphs[0].text


def test_fill_invoice_template_preserves_bold_formatting(tmp_path: Path):
    data = TimesheetData(job_id="2026/9999/#1/1", period="September 2026", total_amount=123.45)
    output_path = tmp_path / "invoice_out.docx"

    fill_invoice_template(
        SAMPLE_DATA / "invoice_template.docx",
        output_path,
        data,
        vendor_id="000000",
        invoice_date=date(2026, 9, 15),
    )

    doc = docx.Document(str(output_path))
    job_id_run = doc.tables[2].rows[2].cells[0].paragraphs[0].runs[0]

    assert job_id_run.bold is True


def test_parse_purchase_order_pdf_reads_the_sample_pdf():
    data = parse_purchase_order_pdf(SAMPLE_DATA / "sample_purchase_order.pdf")

    assert data is not None
    assert data.job_id == "2026/1234/#1/1"
    assert data.period == "September 2026"
    assert data.total_amount == 100.0


def test_scheduler_flow_fills_invoice_from_purchase_order_pdf(tmp_path: Path):
    flow = SchedulerFlow(
        sample_email_path=SAMPLE_DATA / "sample_purchase_order_email.txt",
        timesheet_pdf_path=SAMPLE_DATA / "sample_purchase_order.pdf",
        invoice_template_path=SAMPLE_DATA / "invoice_template.docx",
        invoice_output_dir=tmp_path,
    )

    state = asyncio.run(flow.run_v1_async())

    assert state.email_type == "timesheet"
    assert state.timesheet_data.job_id == "2026/1234/#1/1"
    assert state.timesheet_approval_required is True
    assert state.invoice_output_path is not None
    assert Path(state.invoice_output_path).exists()

    doc = docx.Document(state.invoice_output_path)
    assert doc.tables[2].rows[2].cells[0].paragraphs[0].text == "2026/1234/#1/1"
