from __future__ import annotations

import asyncio
import json
from datetime import date
from pathlib import Path

import docx
import pytest

from scheduler_agents.flows.scheduler_flow import SchedulerFlow
from scheduler_agents.models.state import TimesheetData
from scheduler_agents.tools.invoice_tool import fill_invoice_template
from scheduler_agents.tools.timesheet_tool import (
    extract_purchase_order_via_llm,
    parse_purchase_order_pdf,
    parse_purchase_order_text,
)

SAMPLE_DATA = Path(__file__).resolve().parents[1] / "sample_data"

# Real extracted-text shape from an actual vendor Purchase Order PDF
# (values changed; the layout/wording is what matters for the regexes).
REAL_SHAPED_PO_TEXT = """
PURCHASE ORDER
For the attention of
000000 Jane Doe
123 Example Street
Apt 1
Sample City, Example Country [XX]
Job ID Description
2026/2609/#1/1 000000_Jane Doe_March 2026
Language pair Job type Specialisation
EN-GB » FA interpreting (telephone) Social Services
Delivered to Start date Deadline
Alina Barila Apr 7, 2026 Apr 7, 2026
Calculation unit Quantity Price Amount
1h 40.53 8.0000 324.24
Subtotal € 324.24
2026/2609/#1/1 —Total €324.24
+42 1944314030 http://www.glocco.sk
hello@glocco.sk
Generated by XTRF®
www.xtrf.eu
"""


def test_parse_purchase_order_text_extracts_job_id_period_and_total():
    data = parse_purchase_order_text(REAL_SHAPED_PO_TEXT)

    assert data is not None
    assert data.job_id == "2026/2609/#1/1"
    assert data.period == "March 2026"
    assert data.total_amount == 324.24


def test_parse_purchase_order_text_uses_total_not_subtotal():
    # Subtotal and Total differ (e.g. an adjustment) -- must pick Total.
    text = REAL_SHAPED_PO_TEXT.replace("Subtotal € 324.24", "Subtotal € 300.00")

    data = parse_purchase_order_text(text)

    assert data.total_amount == 324.24


def test_parse_purchase_order_text_returns_none_when_fields_missing():
    assert parse_purchase_order_text("Please find attached the Purchase Order.") is None


def test_fill_invoice_template_updates_only_monthly_fields(tmp_path: Path):
    data = TimesheetData(job_id="2026/9999/#1/1", period="September 2026", total_amount=123.45)
    output_path = tmp_path / "invoice_out.docx"

    fill_invoice_template(
        SAMPLE_DATA / "invoice_template.docx",
        output_path,
        data,
        vendor_id="000000",
        invoice_date=date(2026, 9, 15),
    )

    doc = docx.Document(str(output_path))
    header_table = doc.tables[0]
    line_items_table = doc.tables[2]

    assert header_table.rows[3].cells[1].paragraphs[1].text == "000000/202609"
    assert header_table.rows[3].cells[2].paragraphs[1].text == "15/09/2026"
    assert line_items_table.rows[2].cells[0].paragraphs[0].text == "2026/9999/#1/1"
    assert line_items_table.rows[2].cells[2].paragraphs[0].text == "€ 123.45"
    assert line_items_table.rows[3].cells[2].paragraphs[0].text == "€ 123.45"

    # Static fields (name/address/bill-to) must be untouched.
    assert "Jane Doe" in header_table.rows[1].cells[0].paragraphs[0].text
    assert "GLOCCO" in doc.tables[1].rows[1].cells[0].paragraphs[0].text


def test_fill_invoice_template_preserves_bold_formatting(tmp_path: Path):
    data = TimesheetData(job_id="2026/9999/#1/1", period="September 2026", total_amount=123.45)
    output_path = tmp_path / "invoice_out.docx"

    fill_invoice_template(
        SAMPLE_DATA / "invoice_template.docx",
        output_path,
        data,
        vendor_id="000000",
        invoice_date=date(2026, 9, 15),
    )

    doc = docx.Document(str(output_path))
    job_id_run = doc.tables[2].rows[2].cells[0].paragraphs[0].runs[0]

    assert job_id_run.bold is True


def test_parse_purchase_order_pdf_reads_the_sample_pdf():
    data = parse_purchase_order_pdf(SAMPLE_DATA / "sample_purchase_order.pdf")

    assert data is not None
    assert data.job_id == "2026/1234/#1/1"
    assert data.period == "September 2026"
    assert data.total_amount == 100.0


def test_scheduler_flow_fills_invoice_from_purchase_order_pdf(tmp_path: Path):
    flow = SchedulerFlow(
        sample_email_path=SAMPLE_DATA / "sample_purchase_order_email.txt",
        timesheet_pdf_path=SAMPLE_DATA / "sample_purchase_order.pdf",
        invoice_template_path=SAMPLE_DATA / "invoice_template.docx",
        invoice_output_dir=tmp_path,
    )

    state = asyncio.run(flow.run_v1_async())

    assert state.email_type == "timesheet"
    assert state.timesheet_data.job_id == "2026/1234/#1/1"
    assert state.timesheet_approval_required is True
    assert state.invoice_output_path is not None
    assert Path(state.invoice_output_path).exists()

    doc = docx.Document(state.invoice_output_path)
    assert doc.tables[2].rows[2].cells[0].paragraphs[0].text == "2026/1234/#1/1"


def test_scheduler_flow_prefers_live_pdf_attachment_over_static_path(tmp_path: Path):
    """When receive_email() found and downloaded a real PDF attachment this
    run (live_pdf_attachment_path set), handle_timesheet() must use that --
    not the static local sample -- even if the static path is missing."""

    flow = SchedulerFlow(
        sample_email_path=SAMPLE_DATA / "sample_purchase_order_email.txt",
        timesheet_pdf_path=tmp_path / "does_not_exist.pdf",
        invoice_template_path=SAMPLE_DATA / "invoice_template.docx",
        invoice_output_dir=tmp_path,
    )
    flow.state.live_pdf_attachment_path = str(SAMPLE_DATA / "sample_purchase_order.pdf")

    state = asyncio.run(flow.run_v1_async())

    assert state.timesheet_data is not None
    assert state.timesheet_data.job_id == "2026/1234/#1/1"


def test_extract_purchase_order_via_llm_raises_without_model(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.delenv("MODEL", raising=False)

    with pytest.raises(RuntimeError):
        extract_purchase_order_via_llm("some purchase order text")


def test_extract_purchase_order_via_llm_parses_response(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv("MODEL", "gemini/gemini-1.5-flash")

    class _FakeMessage:
        content = json.dumps({"job_id": "2026/9999/#2/1", "period": "October 2026", "total_amount": 250.5})

    class _FakeChoice:
        message = _FakeMessage()

    class _FakeResponse:
        choices = [_FakeChoice()]

    monkeypatch.setattr(
        "scheduler_agents.tools.timesheet_tool.litellm.completion",
        lambda **kwargs: _FakeResponse(),
    )

    data = extract_purchase_order_via_llm("some unusual purchase order layout")

    assert data.job_id == "2026/9999/#2/1"
    assert data.period == "October 2026"
    assert data.total_amount == 250.5


def test_scheduler_flow_falls_back_to_llm_when_pdf_layout_does_not_match_regex(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """A purchase order PDF with a differently-formatted layout (unusual job
    id, no regex-recognized Total line) must not just fail -- when an LLM
    is configured, it's used as a fallback, same as every other extraction
    path in this project."""

    monkeypatch.setattr("scheduler_agents.flows.scheduler_flow.llm_is_configured", lambda: True)
    monkeypatch.setattr(
        "scheduler_agents.flows.scheduler_flow.read_purchase_order_pdf_text",
        lambda path: "This purchase order uses a layout the regex parser doesn't recognize at all.",
    )
    monkeypatch.setattr(
        "scheduler_agents.flows.scheduler_flow.extract_purchase_order_via_llm",
        lambda text: TimesheetData(job_id="2026/7777/#1/1", period="November 2026", total_amount=99.99),
    )

    flow = SchedulerFlow(
        sample_email_path=SAMPLE_DATA / "sample_purchase_order_email.txt",
        # Exists, but its real text is irrelevant -- read_purchase_order_pdf_text is mocked above.
        timesheet_pdf_path=SAMPLE_DATA / "sample_purchase_order.pdf",
        invoice_template_path=SAMPLE_DATA / "invoice_template.docx",
        invoice_output_dir=tmp_path,
    )
    state = asyncio.run(flow.run_v1_async())

    assert state.timesheet_data.job_id == "2026/7777/#1/1"
    assert any(hook.name == "timesheet_extracted_by_llm" for hook in state.hooks)


def test_scheduler_flow_reports_unparseable_when_llm_fallback_also_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    monkeypatch.setattr("scheduler_agents.flows.scheduler_flow.llm_is_configured", lambda: True)
    monkeypatch.setattr(
        "scheduler_agents.flows.scheduler_flow.read_purchase_order_pdf_text",
        lambda path: "unrecognized layout",
    )

    def failing_extract(text):
        raise RuntimeError("bad JSON from model")

    monkeypatch.setattr("scheduler_agents.flows.scheduler_flow.extract_purchase_order_via_llm", failing_extract)

    flow = SchedulerFlow(
        sample_email_path=SAMPLE_DATA / "sample_purchase_order_email.txt",
        timesheet_pdf_path=SAMPLE_DATA / "sample_purchase_order.pdf",
        invoice_template_path=SAMPLE_DATA / "invoice_template.docx",
        invoice_output_dir=tmp_path,
    )
    state = asyncio.run(flow.run_v1_async())

    assert state.timesheet_data is None
    assert any(hook.name == "timesheet_llm_extraction_failed" for hook in state.hooks)
    assert any(hook.name == "timesheet_pdf_unparseable" for hook in state.hooks)
